FROM python:3.12-slim

WORKDIR /app

COPY main.py .
COPY requirements.txt .

RUN apt-get update && \
	apt-get install -y gcc libffi-dev build-essential && \
	pip install -r requirements.txt && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

CMD ["python3", "main.py"]